---
ntp: 0.be.pool.ntp.org
users:
  - name: benc
    email: ben@cochezconsult.be
    dotfiles: 
      repo: https://github.com/benc/dotfiles.git
      install_command: rake install
mandrill:
  host: smtp.mandrillapp.com
  user: foo@bar.foobar
  api_key: his_fooness_has_left_the_building
database:
  postgres:
    user: postgres
    password: postgres
  ghost:
    name: ghost
    user: ghost
    password: ghost