---
ntp: 0.be.pool.ntp.org
users:
  - name: benc
    password: benc
    email: ben@cochezconsult.be
    dotfiles: 
      repo: https://github.com/benc/dotfiles.git
      install_command: rake install
mandrill:
  host: smtp.mandrillapp.com
  user: foo@bar.foobar
  api_key: his_fooness_has_left_the_building
database:
  postgres:
    user: postgres
    password: e8a48653851e28c69d0506508fb27fc5
  ghost:
    name: ghost
    user: ghost
    password: 71144850f4fb4cc55fc0ee6935badddf
docker:
  user: docker
  password: 05b6053c41a2130afd6fc3b158bda4e6