---
# NOTE:
# ----
# These are development passwords. Production machines should be provisioned with different settings:
# * Copy this yaml to a file 'production.yml' in your ansible root directory
# * Modify the passwords
# * Provide this file when running the playbooks against production:
#  
#       ansible-playbook -i production site.yml --extra-vars "@production.yml"
#
ntp: 0.be.pool.ntp.org
users:
  - name: benc
    password: benc
    email: ben@cochezconsult.be
    github_name: benc
    dotfiles_repo: dotfiles
mandrill:
  host: smtp.mandrillapp.com
  user: foo@bar.foobar
  api_key: his_fooness_has_left_the_building
database:
  postgres:
    user: postgres
    # md5 -s postgres
    password: e8a48653851e28c69d0506508fb27fc5
  ghost:
    name: ghost
    user: ghost
    # md5 -s ghost
    password: 71144850f4fb4cc55fc0ee6935badddf
docker:
  user: docker
  # echo docker | openssl passwd -crypt -stdin
  password: YGB0OKUWgPEsE