---
# NOTE:
# ----
# These are development, thus INSECURE passwords. Production machines should be provisioned with different settings:

# * Copy this yaml to a file 'production.yml' in your ansible root directory
#
# * Modify the passwords
# * Provide this file when running the playbooks against production:
#
#       ansible-playbook -i production site.yml --extra-vars "@production.yml"
#
ntp: 0.be.pool.ntp.org
users:
  - name: benc
    # On Debian, get mkpasswd with:
    #
    #   sudo apt-get install whois
    #
    # Then, generate a password using:
    #
    #   echo benc | mkpasswd --method=SHA-512 -s
    password: $6$wtQ8geXlfiZ$Xgha4T7LP5g7p.69CXHKwKQZOIrPxcT5jUREvMMzYRWnOa/BdAxreBJZ3kpJeaX3/A4jzU7Yn2/LHrH6y66o91
    email: ben@cochezconsult.be
    dotfiles_repo: https://github.com/benc/dotfiles.git
mandrill:
  host: smtp.mandrillapp.com
  user: foo@bar.foobar
  api_key: his_fooness_has_left_the_building
database:
  postgres:
    su_user: postgres
    su_password: postgres
  teamcity:
    user: teamcity
    password: teamcity
  upsource:
    user: upsource
    password: upsource
