---
- name: Create web directory
  file: path={{ ghost.web_dir }} state=directory owner=www-data group=www-data mode=0755

- name: Create temporary build dir
  file: path={{ ghost.build_dir }} state=directory

- name: Copy Dockerfile and config files
  template: src={{ ghost.template_dir }}/{{ item }} dest={{ ghost.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
    - heavyindustries.io.conf
    - config.js

- name: Copy Ghost and related files
  copy: src={{ item }} dest={{ ghost.build_dir }}/{{ item }}
  with_items:
    - ghost-0.4.1.zip
    - N-Coded.zip
    - Uno-master.zip
    - Vapor-master.zip
    - ghostium-master.zip
    - solar-theme-ghost-master.zip

- name: Build Docker image
  command: docker build -q=true -t=benc/ghost -rm . chdir={{ ghost.build_dir }}

- name: Cleanup temporary build dir
  file: path={{ ghost.build_dir }} state=absent

- name: Check if it is already running
  command: docker inspect ghost
  register: docker_inspect_ghost
  ignore_errors: yes

- name: Start ghost instance
  # docker: name=ghost links=postgres:db ports=:80 detach=true image=benc/ghost
  command: docker run -name ghost -link postgres:db -p 80:80 -d benc/ghost
  when: "'No such image or container' in docker_inspect_ghost.stderr"
