---
- include: blog-database.yml
- include: blog-engine.yml

- name: Start blog_engine instance
  docker: name={{ blog_engine.name }} links=postgres:db ports=:80 volumes={{ blog_engine.web_dir }}:/www:rw detach=true image=benc/{{ blog_engine.name }}
