---
- include: blog_engine.yml tags=passenger,blog

- name: Get current running Docker instances
  command: docker ps -a
  register: docker_processes

- name: Start blog_engine instance
  command: docker run -name {{ blog_engine.name }} -link postgres:db -p 80:80 -v {{ blog_engine.web_dir }}:/www:rw -d benc/{{ blog_engine.name }}
  when: not '{{ blog_engine.name }}' in docker_processes.stdout
 
