---
- name: etcd | Create temporary build dir
  file: path={{ etcd.docker.build_dir }} state=directory

- name: etcd | Copy Dockerfile and related config files
  template: src={{ etcd.docker.template_dir }}/{{ item }} dest={{ etcd.docker.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
    - supervisord.conf
    - run_etcd.sh

- name: etcd | Build Docker image
  command: docker build -q=true -t=benc/etcd -rm . chdir={{ etcd.docker.build_dir }}

- name: etcd | Cleanup temporary build dir
  file: path={{ etcd.docker.build_dir }} state=absent

- name: etcd | Check if it is already running
  command: docker inspect etcd
  register: docker_inspect_etcd
  ignore_errors: yes

- name: etcd | Start
  command: docker run -name etcd -d -p 4001:4001 -p 7001:7001 benc/etcd
  when: "'No such image or container' in docker_inspect_etcd.stderr"
