---
- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - mosh
    - zsh
    - git
    - screen
    - ufw
    - curl
    - netcat
    - unzip
    - apt-transport-https

- name: Enable Textmate support
  get_url: url=https://raw.github.com/aurora/rmate/master/rmate dest=/usr/local/bin/rmate mode=0755

- name: Upgrade all safe packages
  apt: upgrade=safe update_cache=yes

- name: Create ssh temporary storage dir
  file: path={{ ssh.public_keys_dir }} state=directory

- name: Copy all ssh public keys to enable further processing
  copy: src=ssh/{{ item.name }}.pub dest={{ ssh.public_keys_dir }}/{{ item.name }}.pub
  with_items: users

- include: ntp.yml tags=ntp
- include: users.yml tags=users
- include: security.yml tags=security
- include: docker.yml tags=docker

- name: Cleanup ssh temporary storage dir
  file: path={{ ssh.public_keys_dir }} state=absent
