---
- name: Ruby | Install rvm dependencies
  apt: update_cache=yes pkg={{ item }} state=present
  with_items:
    - curl
    - build-essential
    - autoconf 
    - bison 
    - libssl-dev 
    - libyaml-dev 
    - libreadline6 
    - libreadline6-dev 
    - zlib1g 
    - zlib1g-dev

- name: Ruby | Install rvm (multi user installation)
  shell: \curl -L https://get.rvm.io | sudo bash -s stable creates=/usr/local/rvm/bin/rvm
  
- name: Ruby | rvm get stable
  shell:  bash -lc "rvm get stable --auto-dotfiles" 

- name: Ruby | Install rubies
  shell: bash -lc "rvm install {{ item }} --verify-downloads 1" creates=/usr/local/rvm/rubies/ruby-{{ item }}
  with_items:
    - 1.8.7-p370
    - 1.9.2-p290
    - 1.9.3-p484
    - 2.1.0

- name: Ruby | Set default ruby
  shell: bash -lc "rvm use 2.1.0 --default"

- name: Ruby | Install basic tooling
  gem: name={{ item }} state=latest executable=/usr/local/rvm/rubies/default/bin/gem
  with_items:
    - rake
    - bundler