---
- name: Security | Create ssh temporary storage dir
  file: path={{ ssh.public_keys_dir }} state=directory
  
- name: Security | Copy all ssh public keys to enable further processing
  copy: src=ssh/{{ item.name }}.pub dest={{ ssh.public_keys_dir }}/{{ item.name }}.pub
  with_items: users
  
- name: Security | Replace vagrant default (and insecure) public key with the configured users
  assemble: src={{ ssh.public_keys_dir }} dest=/home/vagrant/.ssh/authorized_keys mode=0600 owner=vagrant
  when: ansible_ssh_user == 'vagrant'
  
- name: Security | Configure and enable ufw
  command: ufw {{ item }}
  with_items:
    - default deny
    - logging on
    - allow ssh/tcp
    - allow http/tcp
    - --force enable

