- name: Users | Create user accounts
  user: name={{ item.name }} password={{ item.password }} state=present shell=/usr/bin/zsh groups=rvm,sudo,staff createhome=yes
  with_items: users
  
- name: Users | Configure SSH for created users
  file: path=/home/{{ item.name }}/.ssh state=directory mode=0700 owner={{ item.name }} group={{ item.name }}
  with_items: users

- name: Users | Add authorized_keys for created users
  template: src=ssh/{{ item.name }}.pub dest=/home/{{ item.name }}/.ssh/authorized_keys mode=0600 owner={{ item.name }} group={{ item.name }}
  with_items: users

- name: Users | Get zprezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=/home/{{ item.name }}/.zprezto
  sudo_user: "{{ item.name }}"
  with_items: users
 
- name: Users | Get homesick
  gem: name=homesick state=latest executable=/usr/local/rvm/rubies/default/bin/gem
  
- name: Users | Get dotfiles
  shell: bash -lc "homesick clone {{ item.github_name }}/{{ item.dotfiles_repo }}" creates=/home/{{ item.name }}/.homesick/repos/{{ item.dotfiles_repo }}
  sudo_user: "{{ item.name }}"
  with_items: users

- name: Users | Update dotfiles
  shell: bash -lc "homesick pull {{ item.dotfiles_repo }}"
  sudo_user: "{{ item.name }}"
  with_items: users
    
- name: Users | Symlink dotfiles
  sudo_user: "{{ item.name }}"
  shell: bash -lc "homesick -f symlink {{ item.dotfiles_repo }}" 
  with_items: users
