- name: Users | Get rmc
  get_url: url=http://thoughtbot.github.io/rcm/debs/rcm_1.2.0_all.deb dest=/tmp

- name: Users | Install rmc
  shell: dpkg -i /tmp/rcm_1.2.0_all.deb
    
- name: Users | Create user accounts
  user: name={{ item.name }} password={{ item.password }} state=present shell=/usr/bin/zsh groups=sudo,staff createhome=yes
  with_items: users

- name: Users | Add authorized_keys for created users
  authorized_key: user={{ item.name }} key="{{ lookup('file', 'ssh/' + item.name + '.pub') }}"
  with_items: users
    
- name: Users | Get zprezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=/home/{{ item.name }}/.zprezto
  sudo_user: "{{ item.name }}"
  with_items: users
  
- name: Users | Get dotfiles
  git: repo="{{ item.dotfiles_repo }}" dest=/home/{{ item.name }}/.dotfiles
  sudo_user: "{{ item.name }}"
  with_items: users
    
- name: Users | Symlink dotfiles
  shell: "rcup rcrc && rcup" 
  sudo_user: "{{ item.name }}"
  with_items: users
