---
- name: Create temporary build dir
  file: path={{ passenger.build_dir }} state=directory

- name: Copy Dockerfile and related config files
  template: src={{ passenger.template_dir }}/{{ item }} dest={{ passenger.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
    - supervisord.conf
    - nginx.conf
      
- name: Build Docker image
  command: docker build -t benc/passenger . chdir={{ passenger.build_dir }}
