---
- name: Data only container | Create temporary build dir
  file: path={{ postgres.data_docker.build_dir }} state=directory

- name: Data only container | Copy Dockerfile and related config files
  template: src={{ postgres.data_docker.template_dir }}/{{ item }} dest={{ postgres.data_docker.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
      
- name: Data only container | Build Docker image
  command: docker build -q=true -t=benc/postgres_data . chdir={{ postgres.data_docker.build_dir }}

- name: Data only container | Start
  docker: name=postgres_data detach=true image=benc/postgres_data