---
- name: Create temporary build dir
  file: path={{ postgres.docker.build_dir }} state=directory

- name: Copy Dockerfile and related config files
  template: src={{ postgres.docker.template_dir }}/{{ item }} dest={{ postgres.docker.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
    - postgresql.conf
    - pg_hba.conf
    - supervisord.conf
    - start_postgres.sh
      
- name: Build Docker image
  command: docker build -q=true -t=benc/postgres -rm . chdir={{ postgres.docker.build_dir }}

- name: Create temporary build dir
  file: path={{ postgres.data_docker.build_dir }} state=directory

- name: Copy Dockerfile and related config files
  template: src={{ postgres.data_docker.template_dir }}/{{ item }} dest={{ postgres.data_docker.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
      
- name: Build Docker image
  command: docker build -q=true -t=benc/postgres_data -rm . chdir={{ postgres.data_docker.build_dir }}

#- name: Stop data only container
#  command: docker stop postgres_data
#  
#- name: Stop postgres docker instance
#  command: docker stop postgres

- name: Start data only container
  command: docker run -name postgres_data -v /data -d benc/postgres_data
  
- name: Start postgres docker instance
  command: docker run -name postgres -d -p 5432:5432 -volumes-from postgres_data -e POSTGRES_USER={{ postgres.user }} -e POSTGRES_PASSWORD={{ postgres.password }} benc/postgres
