---
- name: Create temporary build dir
  file: path={{ postgres.build_dir }} state=directory

- name: Copy Dockerfile and related config files
  template: src={{ postgres.template_dir }}/{{ item }} dest={{ postgres.build_dir }}/{{ item }}
  with_items:
    - Dockerfile
    - postgresql.conf
    - pg_hba.conf
    - supervisord.conf
      
- name: Build Docker image
  command: docker build -t benc/postgres . chdir={{ postgres.build_dir }}
